// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type User struct {
	ID      int32  `json:"id"`
	Login   string `json:"login"`
	Name    string `json:"name"`
	Surname string `json:"surname"`
}
