name: ci
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  build:
    services:
        postgres:
          image: postgres:12
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: qwerty
            POSTGRES_DB: postgres
          ports:
            - 5433:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    name: 🔨Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: go-migrate install
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/migrate
          which migrate
      - name: migrations
        run: make migrateUp
      - name: Build
        run: go build -v ./src/
      - name: Test
        run: make test